### ISSUE TITLE
use scheme functions for cons car and cdr

### ISSUE THREAD

**Issue by erratic-c-programmer** [erjiang/foxscheme#14]
cons, car and cdr can be trivially implemented in scheme-- why not do that instead?

**Comment by erjiang** [comment]
How would pairs be represented? As lambdas?

It's implemented in JS mainly because Pair is a "native" object and needs "native" functions to manipulate them. I would imagine it would be a large perf hit to do otherwise.

**Comment by erratic-c-programmer** [comment]
Ah, so performance reasons :p 

But yeah I meant with functions, a la SICP haha
